### ISSUE TITLE
Exception when opening REPL windows after relaunching VS 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#100]
VS 2013.4
NTVS 1.0.30129.00
PoshTools: the build for bugbash 2-5

Repre:
1. Start VS
2. Create a powershell script project
3. Open the Powershell REPL window, and the NTVS REPL window
4. Execute couple of Powershell scripts in the PS REPL windows
5. Close VS
6. Restart VS

Result:
Exception when opening the PS REPL window.  Here is the callstack.

```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\jinglou\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml".

Exception details:
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```

**Comment by jinglouMSFT** [comment]
This seems to only happen if i had NTVS REPL window and the PS REPL window open before I close VS. If i only have PS REPL window before close VS, then there is no problem after relaunching VS.

**Comment by ASayre** [comment]
Fixed as part of recent ReGuidding work

**Comment by ASayre** [comment]
reopening, as it no longer crashes, but if they're both open at the same time, Then one of them will have an error

```
Construction of frame content failed.&#x000D;&#x000A;Frame identifier: ST:1:0:{2227c503-8daf-44e6-bff6-222088de83e0}&#x000D;&#x000A;Frame caption: PowerShell Debug Interactive&#x000D;&#x000A;Exception details:&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```
