### ISSUE TITLE
VS crashes when quickly typing and entering 

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#344]
Call stack:
An unhandled exception is about to terminate the process.  Exception info:
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

Parameter name: length

   at System.String.Substring(Int32 startIndex, Int32 length)

   at PowerShellTools.Classification.RegionAndBraceMatchingService.AddBraceMatchingAndOutlinesForString(Int32 spanStart, IDictionary`2 startBraces, IDictionary`2 endBraces, ICollection`1 regions, String text, Token stringToken) in d:\Github\poshtools\PowerShellTools\Classification\ClassifierServices.cs:line 269

   at PowerShellTools.Classification.RegionAndBraceMatchingService.GetRegionsAndBraceMatchingInformation(String spanText, Int32 spanStart, IList`1 generatedTokens, Dictionary`2& startBraces, Dictionary`2& endBraces, List`1& regions) in d:\Github\poshtools\PowerShellTools\Classification\ClassifierServices.cs:line 190

   at PowerShellTools.Classification.PowerShellTokenizationService.Tokenize(ITrackingSpan spanToTokenize, String spanText) in d:\Github\poshtools\PowerShellTools\Classification\PowerShellTokenizationService.cs:line 150

   at PowerShellTools.Classification.PowerShellTokenizationService.<>c__DisplayClass1.<StartTokenization>b__0(Object _) in d:\Github\poshtools\PowerShellTools\Classification\PowerShellTokenizationService.cs:line 70

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

   at Microsoft.VisualStudioTools.Project.UIThread.<Initialize>b__9(Object sender, UnhandledExceptionEventArgs args) in d:\Github\poshtools\PowerShellTools\Project\SharedProject\UIThread.cs:line 228

   at System.String.Substring(Int32 startIndex, Int32 length)

   at PowerShellTools.Classification.RegionAndBraceMatchingService.AddBraceMatchingAndOutlinesForString(Int32 spanStart, IDictionary`2 startBraces, IDictionary`2 endBraces, ICollection`1 regions, String text, Token stringToken) in d:\Github\poshtools\PowerShellTools\Classification\ClassifierServices.cs:line 269

   at PowerShellTools.Classification.RegionAndBraceMatchingService.GetRegionsAndBraceMatchingInformation(String spanText, Int32 spanStart, IList`1 generatedTokens, Dictionary`2& startBraces, Dictionary`2& endBraces, List`1& regions) in d:\Github\poshtools\PowerShellTools\Classification\ClassifierServices.cs:line 190

   at PowerShellTools.Classification.PowerShellTokenizationService.Tokenize(ITrackingSpan spanToTokenize, String spanText) in d:\Github\poshtools\PowerShellTools\Classification\PowerShellTokenizationService.cs:line 150

   at PowerShellTools.Classification.PowerShellTokenizationService.<>c__DisplayClass1.<StartTokenization>b__0(Object _) in d:\Github\poshtools\PowerShellTools\Classification\PowerShellTokenizationService.cs:line 70

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by HuanhuanSunMSFT** [comment]
Jing also ran into a similar issue causing VS crashes
![bug](https://cloud.githubusercontent.com/assets/10081208/6974197/8f8ced28-d945-11e4-9020-d0f537708788.png)

**Comment by ASayre** [comment]
We believe that we fixed this with #338
