### ISSUE TITLE
Host Process Pipeline busy when F5'd a psm file

### ISSUE THREAD

**Issue by ASayre** [microsoft/poshtools#443]
Enabling/disabling breakpoint here, F5'd:

![image](https://cloud.githubusercontent.com/assets/10080679/7227389/11871494-e705-11e4-9874-84a31f1fd4ba.png)

```
PowerShellTools.DebugEngine.Engine: 02:27:27,525 - 1 - DEBUG - Attaching the debug engine.
PowerShellTools.DebugEngine.ScriptProgramNode: 02:27:27,540 - 1 - DEBUG - ScriptProgramNode: Entering GetEngineInfo
PowerShellTools.DebugEngine.ScriptProgramNode: 02:27:27,540 - 1 - DEBUG - ScriptProgramNode: Entering GetHostName
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,540 - 1 - DEBUG - RunspaceRequest
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,540 - 1 - DEBUG - EngineCreated
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,540 - 1 - DEBUG - ProgramCreated
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,540 - 1 - DEBUG - EngineLoaded
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,556 - 1 - DEBUG - DebugEntryPoint
PowerShellTools.DebugEngine.ScriptProgramNode: 02:27:27,556 - 1 - DEBUG - ScriptProgramNode: Entering GetProgramId cc3bd7bb-42f4-4b6f-b92b-d0410b7030ff
PowerShellTools.DebugEngine.Engine: 02:27:27,556 - 1 - DEBUG - Engine: CreatePendingBreakPoint
PowerShellTools.DebugEngine.ScriptBreakpoint: 02:27:27,587 - 1 - INFO - ScriptBreakPoint: C:\Users\AndreSay\documents\visual studio 2015\Projects\PowerShellModuleProject3\PowerShellModuleProject3\Module.psm1 5 0
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,587 - 1 - DEBUG - BreakpointAdded
PowerShellTools.DebugEngine.BreakpointManager: 02:27:27,587 - 1 - INFO - SetBreakpoint: C:\Users\AndreSay\documents\visual studio 2015\Projects\PowerShellModuleProject3\PowerShellModuleProject3\Module.psm1 5 0
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,603 - 15 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Checking runspace availability: Available
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,603 - 15 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Checking runspace availability: Available
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,618 - 15 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Setting breakpoint ...
PowerShellTools.DebugEngine.ScriptBreakpoint: 02:27:27,634 - 1 - DEBUG - ScriptBreakpoint: Enable
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,634 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Breakpoint updated: Set Line breakpoint on 'C:\Users\AndreSay\documents\visual studio 2015\Projects\PowerShellModuleProject3\PowerShellModuleProject3\Module.psm1:5'
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,650 - 1 - DEBUG - BreakpointEnabled
PowerShellTools.DebugEngine.ScriptDebugger: 02:27:27,650 - 26 - INFO - Execute
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,650 - 15 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Setting execution policy
PowerShellTools.DebugEngine.BreakpointManager: 02:27:27,650 - 1 - INFO - Enable breakpoint: C:\Users\AndreSay\documents\visual studio 2015\Projects\PowerShellModuleProject3\PowerShellModuleProject3\Module.psm1 5 0
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,665 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Checking runspace availability: Available
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,665 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Start executing ps script ...
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,665 - 15 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Getting PSBreakpoint ...
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,665 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Enable breakpoint ...
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:27,728 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:PowershellHostService: The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.
Exception thrown: 'System.ServiceModel.FaultException' in mscorlib.dll
PowerShellTools.DebugEngine.BreakpointManager: 02:27:27,941 - 1 - ERROR - Failed to Enable breakpoint.
System.ServiceModel.FaultException: There is a problem in the powershell host service.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at PowerShellTools.Common.ServiceManagement.DebuggingContract.IPowershellDebuggingService.EnableBreakpoint(PowershellBreakpoint bp, Boolean enable)
   at PowerShellTools.DebugEngine.BreakpointManager.EnableBreakpoint(ScriptBreakpoint breakpoint, Int32 fEnable) in E:\OpenSource\Repos\poshtools\PowerShellTools\DebugEngine\BreakpointManager.cs:line 178
PowerShellTools.DebugEngine.ScriptBreakpoint: 02:27:27,946 - 1 - DEBUG - ScriptBreakpoint: Virtualize
PowerShellTools.DebugEngine.ScriptBreakpoint: 02:27:27,951 - 1 - DEBUG - ScriptBreakpoint: Bind
PowerShellTools.DebugEngine.EngineEvents: 02:27:27,953 - 1 - DEBUG - Breakpoint
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:33,169 - 6 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:DebuggerFinished
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:33,171 - 5 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:ClearBreakpoints
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:33,181 - 5 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Breakpoint updated: Removed Line breakpoint on 'C:\Users\AndreSay\documents\visual studio 2015\Projects\PowerShellModuleProject3\PowerShellModuleProject3\Module.psm1:5'
PowerShellTools.DebugEngine.EngineEvents: 02:27:33,188 - 1 - DEBUG - OutputString
PowerShellTools.DebugEngine.EngineEvents: 02:27:33,198 - 14 - DEBUG - ProgramDestroyed
PowerShellTools.DebugEngine.EngineEvents: 02:27:33,198 - 26 - DEBUG - ProgramDestroyed
PowerShellTools.ServiceManagement.PowershellHostProcessHelper: 02:27:33,198 - 13 - DEBUG - [bbfb5cb5-6979-4b8f-ad0d-62b421cde331]:Checking runspace availability: Available
```

**Comment by ASayre** [comment]
Distilled:
F5'ing the PSM, and then we try to set the breakpoint on an item we weren't really F5'ing.
